import { Nunito } from "next/font/google";
import ToasterHost from "@/components/ui/ToasterHost";
import "./globals.css";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata = {
  title: "Logica test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${nunito.variable} min-h-full antialiased xl:h-full`}>
      <body className="flex min-h-[100dvh] flex-col overflow-x-hidden overflow-y-auto font-sans xl:h-full xl:max-h-[100dvh] xl:overflow-hidden">
        {children}
        <ToasterHost />
      </body>
    </html>
  );
}
